// automatically generated by the FlatBuffers compiler, do not modify

package io.dashbase.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StringCol extends Table {
  public static StringCol getRootAsStringCol(ByteBuffer _bb) { return getRootAsStringCol(_bb, new StringCol()); }
  public static StringCol getRootAsStringCol(ByteBuffer _bb, StringCol obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public StringCol __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String key() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer keyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String value() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer valueAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createStringCol(FlatBufferBuilder builder,
      int keyOffset,
      int valueOffset) {
    builder.startObject(2);
    StringCol.addValue(builder, valueOffset);
    StringCol.addKey(builder, keyOffset);
    return StringCol.endStringCol(builder);
  }

  public static void startStringCol(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addKey(FlatBufferBuilder builder, int keyOffset) { builder.addOffset(0, keyOffset, 0); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(1, valueOffset, 0); }
  public static int endStringCol(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

