// automatically generated by the FlatBuffers compiler, do not modify

package io.dashbase.flatbuffers;

public final class Type {
  private Type() { }
  public static final byte Text = 0;
  public static final byte Meta = 1;
  public static final byte Id = 2;
  public static final byte Int = 3;
  public static final byte Float = 4;
  public static final byte Double = 5;

  public static final String[] names = { "Text", "Meta", "Id", "Int", "Float", "Double", };

  public static String name(int e) { return names[e]; }
}

