version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - run:
          name: Setup AWS credentials
          command: |
            mkdir ~/.aws
            echo -e "[default]\naws_access_key_id=${AWS_ACCESS_KEY_ID}\naws_secret_access_key=${AWS_SECRET_ACCESS_KEY}\n" > ~/.aws/credentials
            chmod 600 ~/.aws/*

      - restore_cache:
          keys:
            - gradle-idl-{{ checksum "build.gradle" }}
            - gradle-idl- # used if checksum fails

      - run: ./gradlew testClasses

      - save_cache:
          key: gradle-idl-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

      - run: ./gradlew build

      - store_test_results:
          path: build/test-results

      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./gradlew publish
            fi