version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2- # used if checksum fails

      - run: mvn dependency:go-offline

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run: mvn test

      - store_test_results:
          path: target/surefire-reports